name-template: 'TJAPlayer3 v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
branches:
  - 'master'
template: |
  ## Changes
  
  $CHANGES
categories:
  - title: 'Enhancements'
    label: 'enhancement'
  - title: 'Bug Fixes'
    label: 'bug'
  - title: 'Maintenance'
    label: 'chore'