name: build

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up NuGet
      uses: nuget/setup-nuget@v1
    - name: Restore NuGet Packages
      run: nuget restore $Env:GITHUB_WORKSPACE\TJAPlayer3.sln
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build the Solution
      run: MSBuild.exe $Env:GITHUB_WORKSPACE\TJAPlayer3.sln -p:Configuration=Release
      timeout-minutes: 5
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TJAPlayer3-Develop-ReWrite
        path: Test
    - name: Create a Release
      uses: actions/create-release@v1
      with:
        tag_name: TJAPlayer3-Develop-ReWrite
        release_name: ${{ github.event.head_commit.message }}
        body_path: Test
