name: build

on: [push]

jobs:
  build:

    runs-on: windows-2019
    echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    - name: Set up NuGet
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Restore NuGet Packages
      run: echo "::`echo -n ${{ github.token }} | sha256sum | head -c 64`::"
      run: nuget restore $Env:GITHUB_WORKSPACE\TJAPlayer3.sln
    - name: Set up MSBuild
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build the Solution
      run: MSBuild.exe $Env:GITHUB_WORKSPACE\TJAPlayer3.sln -p:Configuration=Release
      timeout-minutes: 5
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TJAPlayer3-Develop-ReWrite
        path: Test